### ISSUE TITLE
 Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by naviat** [tomochain/tomox-sdk#78]
```
tomochainINFO 04:53:14 at ws/connection.go:84 in readHandler():orders/NEW_ORDER
tomochainDEBU 04:53:14 at endpoints/order.go:595 in handleWSNewOrder():Payload: map[amount:10000000000000000 baseToken:0x4d7ea2ce949216d6b120f3aa10164173615a2b6c exchangeAddress:0x0D3ab14BBaD3D99F4203bd7a11aCB94882050E7e hash:0x42673c7ecd1289d9ee022045a8026db2e5e80a3e7017051709c56298ec401e4e makeFee:1 nonce:23 pricepoint:2001000000000000000000 quoteToken:0x0000000000000000000000000000000000000001 side:BUY signature:map[R:0x4ff857e070fe67a315db212d15d37f06cac2f83a59f49ef25ac7521d1cf56327 S:0x0c99fc943ed1f7f62e081bc512c682fe05c64ababa0f8e968cb43eaaf5db5de9 V:28] takeFee:1 userAddress:0x8fB1047e874d2e472cd08980FF8383053dd83102]#
tomochainINFO 04:53:14 at ws/orders.go:52 in RegisterOrderConnection():Registering new order connection
tomochainINFO 04:53:14 at ws/orders.go:59 in RegisterOrderConnection():Registering a new order connection
tomochainINFO 04:53:14 at ws/connection.go:146 in RegisterConnectionUnsubscribeHandler():Registering a new unsubscribe handler
tomochainINFO 04:53:14 at ws/orders.go:62 in RegisterOrderConnection():Number of connections for this address: %v 1
tomochainINFO 04:53:14 at ws/main.go:6 in isClientConnected():Client is connected
tomochainINFO 04:53:14 at services/validator.go:37 in ValidateAvailableBalance():ValidateAvailableBalance start...
tomochainINFO 04:53:14 at ethereum/provider.go:214 in Balance():GetBalanceAt: 904625697166532776746648320380374280103671755200326948049329775061821325312
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xce41d3]

goroutine 16974 [running]:
github.com/tomochain/tomox-sdk/daos.(*OrderDao).AddNewOrder(0xc00078c1e0, 0xc000870340, 0xc0007ea370, 0xae, 0x0, 0x0)
        /home/ubuntu/tomox-sdk/daos/order.go:1013 +0x3c3
github.com/tomochain/tomox-sdk/engine.(*OrderBook).newOrder(0xc000cf2480, 0xc000870340, 0x0, 0x0)
        /home/ubuntu/tomox-sdk/engine/orderbook.go:71 +0xb0
github.com/tomochain/tomox-sdk/engine.(*Engine).handleNewOrder(0xc00009ab40, 0xc000cd4500, 0x265, 0x267, 0x0, 0x0)
        /home/ubuntu/tomox-sdk/engine/engine.go:130 +0x38d
github.com/tomochain/tomox-sdk/engine.(*Engine).HandleOrders(0xc00009ab40, 0xc001149020, 0x0, 0x0)
        /home/ubuntu/tomox-sdk/engine/engine.go:78 +0x2cc
created by github.com/tomochain/tomox-sdk/rabbitmq.(*Connection).SubscribeOrders.func1.1
        /home/ubuntu/tomox-sdk/rabbitmq/orders.go:32 +0x20e
```

**Comment by nghiatomo** [comment]
fixed
