### ISSUE TITLE
exception server

### ISSUE THREAD

**Issue by nghiatomo** [tomochain/tomox-sdk#82]
tomochainINFO 04:58:55 at ws/connection.go:48 in func1():Closing connection
tomochainINFO 04:58:55 at ws/notification.go:35 in func1():%v connections before unsubscription 2
tomochainINFO 04:58:55 at ws/notification.go:28 in func1():In unsubscription handler
tomochainINFO 04:58:55 at ws/notification.go:35 in func1():%v connections before unsubscription 2
panic: runtime error: slice bounds out of range

goroutine 2959 [running]:
github.com/tomochain/tomox-sdk/ws.NotificationSocketUnsubscribeHandler.func1(0xc0004bd2c0)
	/home/ubuntu/tomox-sdk/ws/notification.go:38 +0x763
created by github.com/tomochain/tomox-sdk/ws.(*Client).closeConnection
	/home/ubuntu/tomox-sdk/ws/client.go:56 +0x85
panic: runtime error: slice bounds out of range

goroutine 2960 [running]:
github.com/tomochain/tomox-sdk/ws.NotificationSocketUnsubscribeHandler.func1(0xc0004bd2c0)
	/home/ubuntu/tomox-sdk/ws/notification.go:38 +0x763
created by github.com/tomochain/tomox-sdk/ws.(*Client).closeConnection
	/home/ubuntu/tomox-sdk/ws/client.go:56 +0x85

**Comment by nghiatomo** [comment]
fixed in e33dd32ce9ad94f9faed603c5a8e46f6c265b495 commit
