### ISSUE TITLE
error: concurrent map read and map write

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomox-sdk#94]
```
NFO 09:51:15 at daos/order.go:984 in Aggregate():[map[$match:map[side:BUY status:map[$in:[NEW OPEN PARTIAL_FILLED]]]] map[$group:map[_id:map[baseToken:$baseToken pairName:$pairName quoteToken:$quoteToken] bestPrice:map[$max:$price] orderCount:map[$sum:1] orderVolume:map[$sum:map[$subtract:[map[$toDecimal:$quantity] map[$toDecimal:$filledAmount]]]]]]]
INFO 09:51:15 at daos/order.go:984 in Aggregate():[map[$match:map[side:SELL status:map[$in:[NEW OPEN PARTIAL_FILLED]]]] map[$group:map[_id:map[baseToken:$baseToken pairName:$pairName quoteToken:$quoteToken] bestPrice:map[$min:$price] orderCount:map[$sum:1] orderVolume:map[$sum:map[$subtract:[map[$toDecimal:$quantity] map[$toDecimal:$filledAmount]]]]]]]
1568713755000RAW DATA: map[_id:map[baseToken:0x4d7eA2cE949216D6b120f3AA10164173615A2b6C pairName:BTC/TOMO quoteToken:0x0000000000000000000000000000000000000001] close:27927320000000000000000 closeTime:2019-09-17 09:49:15.03 +0000 UTC count:239 high:30000000000000000000000 low:27756030000000000000000 open:29000000000000000000000 openTime:2019-09-17 07:41:04.899 +0000 UTC volume:6788600737812105940]
2019-09-17 07:41:04.899 +0000 UTC
2019-09-17 09:49:15.03 +0000 UTC
INFO 09:51:18 at daos/order.go:984 in Aggregate():[map[$match:map[side:BUY status:map[$in:[NEW OPEN PARTIAL_FILLED]]]] map[$group:map[_id:map[baseToken:$baseToken pairName:$pairName quoteToken:$quoteToken] bestPrice:map[$max:$price] orderCount:map[$sum:1] orderVolume:map[$sum:map[$subtract:[map[$toDecimal:$quantity] map[$toDecimal:$filledAmount]]]]]]]
INFO 09:51:18 at daos/order.go:984 in Aggregate():[map[$match:map[side:SELL status:map[$in:[NEW OPEN PARTIAL_FILLED]]]] map[$group:map[_id:map[baseToken:$baseToken pairName:$pairName quoteToken:$quoteToken] bestPrice:map[$min:$price] orderCount:map[$sum:1] orderVolume:map[$sum:map[$subtract:[map[$toDecimal:$quantity] map[$toDecimal:$filledAmount]]]]]]]
1568713755000fatal error: concurrent map read and map write
INFO 09:51:18 at ws/connection.go:48 in func1():Closing connection

goroutine 26301 [running]:
runtime.throw(0xf5da8b, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc002328760 sp=0xc002328730 pc=0x433bd2
runtime.mapaccess1_fast64(0xdcd0a0, 0xc000687bc0, 0xc001e284c0, 0x56)
        /usr/local/go/src/runtime/map_fast64.go:21 +0x1b3 fp=0xc002328788 sp=0xc002328760 pc=0x417303
github.com/tomochain/tomox-sdk/ws.(*OrderBookSocket).UnsubscribeChannel(...)
        /home/ubuntu/go/src/github.com/tomochain/tomox-sdk/ws/orderbook.go:71
github.com/tomochain/tomox-sdk/ws.(*OrderBookSocket).UnsubscribeChannelHandler.func1(0xc001e284c0)
        /home/ubuntu/go/src/github.com/tomochain/tomox-sdk/ws/orderbook.go:59 +0x86 fp=0xc0023287d8 sp=0xc002328788 pc=0xb3a056
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0023287e0 sp=0xc0023287d8 pc=0x463211
created by github.com/tomochain/tomox-sdk/ws.(*Client).closeConnection
        /home/ubuntu/go/src/github.com/tomochain/tomox-sdk/ws/client.go:56 +0x85

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f5f40a98870, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000327c18, 0x72, 0x0, 0x0, 0xf16b70)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000327c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000327c00, 0xc000046570, 0xc000046500, 0x411f69)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000d60d8, 0xc000a37d18, 0x91e86e6e, 0xcfc0cc5ad33f55e5)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0000d60d8, 0xc000a37d40, 0x4c06d6, 0x5d80ac91)
        /usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc0000d60d8, 0xc000a37d90, 0x18, 0xc000000180, 0x6dd6c4)
        /usr/local/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc00036ad00, 0x1204220, 0xc0000d60d8, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc00036ad00, 0xc00036ad00, 0x11efc00)
        /usr/local/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(...)
        /usr/local/go/src/net/http/server.go:3037
github.com/tomochain/tomox-sdk/server.Start()
        /home/ubuntu/go/src/github.com/tomochain/tomox-sdk/server/server.go:62 +0x498
main.main()
        /home/ubuntu/go/src/github.com/tomochain/tomox-sdk/main.go:6 +0x20

goroutine 20 [chan receive, 130 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000d8b40, 0xc0000d8a80)
        /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0xdd

goroutine 21 [chan receive, 130 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000d8b40, 0xc0000d8ae0)
        /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x109

goroutine 22 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).remote(0xc00025e000, 0x0, 0x0, 0x0, 0x7f5f40b00b00)
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/consensus/ethash/sealer.go:304 +0x514
created by github.com/ethereum/go-ethereum/consensus/ethash.New
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/consensus/ethash/ethash.go:496 +0x35c

goroutine 23 [chan receive, 130 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00025c1c0)
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive, 130 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00025c1c0)
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.15/core/tx_cacher.go:55 +0x9f

```

**Comment by nghiatomo** [comment]
fixed in commit 9e0a0223f444f9a148ee6bda243eb8b6f62528a0
